# Generated by Django 6.0.6 on 2026-09-08 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0004_category_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=50, verbose_name="Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                ("adress", models.TextField(verbose_name="Teslimat Adresi")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Posta Kodu"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Şehir")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Sipariş Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("proccessing", "Hazırlanıyor"),
                            ("shipped", "Kargoya Verildi"),
                            ("completed", "Tamamlandı"),
                            ("canceled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False, verbose_name="Ödeme Yapıldı Mı?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş",
                "verbose_name_plural": "Siparişler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Satış Fiyatı"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Adet"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Sipraiş",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="products.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş Kalemi",
                "verbose_name_plural": "Sipariş Kalemleri",
            },
        ),
    ]
