# Generated by Django 6.0.6 on 2026-09-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="adress",
            new_name="address",
        ),
    ]
