# Generated by Django 6.0.6 on 2026-08-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="user",
        ),
    ]
