# Generated by Django 6.0.6 on 2026-08-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_products_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
