# Generated by Django 6.0.6 on 2026-08-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_products_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="URL İsmi (Slug)",
            ),
        ),
    ]
