# Generated by Django 6.0.6 on 2026-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=10, verbose_name="Stok Adedi"),
        ),
    ]
