# Generated by Django 6.0.6 on 2026-09-13 22:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_favourites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favourites",
            new_name="Favourite",
        ),
    ]
