# Generated by Django 6.0.6 on 2026-09-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_favorite_delete_favourite"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="Galeri Görseli"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="products.product",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeri Görseli",
                "verbose_name_plural": "Galeri Görselleri",
            },
        ),
    ]
